name: Check New Proxies

on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario'
        required: false
  schedule:
    - cron: '*/50 * * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests termcolor
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run the code
      run: |
        python main.py
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Fetch New Proxies
        commit_user_name: Vadim287
        commit_user_email: Vadim287@users.noreply.github.com
        commit_author: Vadim287 <Vadim287@users.noreply.github.com>
